Exception on /events/SIST [GET]
Traceback (most recent call last):
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "testApp.py", line 54, in get
    return databaseOperations.getFourteenDaysEvents("SIST")
  File "/home/z/SMART_WeChatMiniProgram/utils/databaseOperations.py", line 138, in getFourteenDaysEvents
    """ % departmentName)
sqlite3.OperationalError: near "WHERE": syntax error
Exception on /events/SIST [GET]
Traceback (most recent call last):
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "testApp.py", line 54, in get
    return databaseOperations.getFourteenDaysEvents("SIST")
  File "/home/z/SMART_WeChatMiniProgram/utils/databaseOperations.py", line 139, in getFourteenDaysEvents
    """ % departmentName)
sqlite3.OperationalError: no such table: BeginTime
Exception on /events/SIST [GET]
Traceback (most recent call last):
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "testApp.py", line 54, in get
    return databaseOperations.getFourteenDaysEvents("SIST")
  File "/home/z/SMART_WeChatMiniProgram/utils/databaseOperations.py", line 139, in getFourteenDaysEvents
    """ % departmentName)
sqlite3.OperationalError: ambiguous column name: Date
